source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CloudTagView_Example' do
  pod 'CloudTagView', :path => '../'
end

target 'CloudTagView_Tests' do
  pod 'CloudTagView', :path => '../'


end
